# Site settings
title: RealGrid Help
email: support@realgrid.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://realgrid.github.io" # the base hostname & protocol for your site
homeurl: "http://www.realgrid.com"
demourl: "http://demo.realgrid.com"
twitter_username: 
github_username: realgrid

# Build settings
markdown: kramdown

# Collections
collections:
  api:
    output: true

type_names:
  - Constants
  - Classes
  - Cell Renderers
  - Cell Editors

object_names:
  - RealGridJS
  - GridBase
  - GridView
  - TreeView
  - DataProvider
  - LocalDataProvider
  - TreeDataProvider
