# Site settings
title: REALGRID help
email: support@realgrid.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.realgrid.com" # the base hostname & protocol for your site
homeurl: "http://www.realgrid.com"
demourl: "http://demo.realgrid.com"
twitter_username: 
github_username: realgrid

# Build settings
markdown: kramdown

# Collections
collections:
  api_fectures:
    output: true

object_names:
  - GridBase
  - GridView
  - TreeView
  - DataProvider
  - LocalDataProvider
  - TreeDataProvider
